sample_info = """{"name":"郭穆よう"}"""
google_credentials = '''
{
  "type": "service_account",
  "project_id": "the-tendril-398702",
  "private_key_id": "ad8928bfdbd9d5e26858c49ae77df2ae1a54e580",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDnC6XsXA9Va8G9\n+7MAaDdgozI2eYgb8IDbeheZyfpuVM3Txc3T85nxzcCIhl0TD4m64WQ8jVL9tim8\nz0P61a6tnN/c9AE/I8wu4h6NecpOkPxKxdlz9r2gpp66X/yYNiKF6Q6F8V5r2fBC\n1t0wj8d5n7UHSwcTfMYq6KkQVdR3+xS99b9iSAqo4Wu3UIffI8I+fQySfA8XAi6J\nHOAK9NiePcHZIUOXb7X4ffkog2y5RGhH1MkYwA8p4BgaXn0m2IIICsOAL+fq2rUl\n4xZdjLTSYmB4R1Pxl6La0lVIoxtUzmUrOhMFKeKJWWRp0sdXdEmTvzrZ9s6lCgTJ\nuWB6AlAvAgMBAAECggEAYwsNP7tfH2EoFocVfvEt/BE5bzy96iw5MNyvzU9WOYHF\nEilTSK6+qXdoN55Ru+AHTMNeMs7qarRyQ+wd2iNL1ETRemhnOGfiGZ75NfCllvR0\nEqGpzBpTw9Bpbr/DCoT6W6lCfoyvy1ALvLta6nxYKH0cH1o8WFA+qxo9jzEb+aop\nxDglZLDS1F6PwMzPJFUR2wnjYtca3R2auY/zqapTMQ4TODmVZHEMOD8p7NJU1F29\nDob0bbI7LQAtmODwcZ4m/FrzNicmWoXN+C3VSK7/RZu+5v+nYsiF7gTXy1HBh+gQ\nE39fP3iodOL4xcsoTyfY2cKOskdLb5eB/i98H/DDUQKBgQD/E6d9E6YvPJVZ0Pw1\n79RMnxebdS+re2F0R0hwmnfIoGgpfkqSBatzqBaT8NO7achPK7T3FXy0HGtFYkJk\nekTv81+6TXgYCJZu20ozX7guGvT+H2M8PWI2/ywpNTgdfCFT0jGa/eJQuCqSDO73\nXYTnDYcIUPN19kZvDaLG2ZvcnQKBgQDn4bowLzFl3SrPHNV1qaeAHnXEZNfrNvOF\n59lhl53ghbR13wzg70p6CGwv1odrab262aQfK2M0Rxs+fUtXLd/DC6EbhZ49CJdp\nEF8jVm9vZt2WhGyglZxK1IjVFrPTyYkAZymAzhLYwEtBTow+GrONvP1YopUJMol4\nfLVHPRrYOwKBgC/uZou3VIQN01bEUZBlF7SqNIpu091aWu65smAOdrHJiqk5ZRPZ\nYuVh0ZRNLcxKzWwrH19Kt1s09+da1nUBENEyH2vnwMhrXLFKHcBXnUl0oVLbXQ9l\nzX3eJ1M6/+dyeuTAW7fvO0bFxKIbMhBjj2THgvdKFuW0uHmHy22oWIR1AoGAPbH8\nVOepj/25byOv07+Q9nCkSt296TJUttMKLoIlmmBYtGflSE/ClBd7mXrNyxF2Tqmr\nljN4EKe+ovC5Q/fLqlyEwArcIEcR6f1WItPTkGNhH7QaJtvHms1TnsaMkBP2JKpO\nC5xIvWzkWPrqK3f1QAgBrDyNxMWyd+FOZibm5pMCgYAsylRbSNywaTuJhM+1m4CH\n9RD3w+bldXMFGmRZfAFKnZ/S9Pm5z2CDiOalq4gxt5+s+MS/uhSyCVBgIYACVbjW\nAoFWQt0ng94PLVOlTYY4QIYLHH3chHjKaErECmhqgAAz5oXA+vhfx1yiCwJDfpxd\nK3AYyqlYvNU6ZoTrUmzGGw==\n-----END PRIVATE KEY-----\n",
  "client_email": "cloud-717@the-tendril-398702.iam.gserviceaccount.com",
  "client_id": "109437934363608276046",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/cloud-717%40the-tendril-398702.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
'''
cotoha = '''
{
  "access_token_url": "https://api.ce-cotoha.com/v1/oauth/accesstokens",
  "base_url": "https://api.ce-cotoha.com/api/dev/",
  "client_id": "iPM8ygGKN9wJFvOJSrugVfOy3zJ1AxNh",
  "client_secret": "nV6YTDyYDpfjrxoG"
}
'''
 hugging_face = ''' 
 { 
 "access_name": "cloud 7", 
 "access_role": "read", 
 "access_token": "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" 
 } 
 '''

